version: 2

jobs:
  'node-lts':
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run: yarn test

  'node-latest':
    docker:
        - image: cimg/node:current
      steps:
        - checkout
        - restore_cache:
            keys:
              - yarn-packages-{{ checksum "yarn.lock" }}
        - run: yarn install --immutable
        - save_cache:
            key: yarn-packages-{{ checksum "yarn.lock" }}
            paths:
              - .yarn/cache
              - .yarn/unplugged
        - run: yarn test

workflows:
  version: 2
  build:
    jobs:
      - 'node-lts'
      - 'node-latest'
